### ISSUE TITLE
What is the slowdown in FPS when processing on-device?

### ISSUE THREAD

**Issue by adammpolak** [geaxgx/depthai_yunet#2]
Is there a noticeable difference in FPS?

**Comment by geaxgx** [comment]
The FPS you get depends on the input size of the models: the bigger, the slower.
Yunet is fast. For the default input size used in the demo.py script (180x320), Yunet is probably faster than 60 fps but you can't notice because the OAK color camera fps is capped to 60 (for an OAKD, less for OAKD lite). So if you run for instance:
`./demo.py -f 70` or `./demo.py -e -f 70`, the measured FPS will be close to 60 fps but still  a few fps faster in edge mode, since the device is fast enough to do all the processing (face detection + post processing) in less than 1/60 s.
On the other side with the larger models (360x640), the edge mode (post processing on device) will be a few fps slower than the host mode (~35 fps vs ~39 fps).

**Comment by adammpolak** [comment]
@geaxgx  because I am using depth for spatiallocationcalculation I can't run faster than 10 fps anyway.

Thank you.
